### ISSUE TITLE
Attributes?

### ISSUE THREAD

**Issue by EvisHome** [akeslo/ouraring-ha#2]
How do you get the attributes to apexcharts-card?

I tried adding attribute, but I am getting N/A for all attributes

**Comment by EvisHome** [comment]
ah .. just noticed the "data" :) and answering my own question.

```
  - platform: template
    sensors:
      deep_sleep:
        value_template: >
          {{ states.sensor.oura_ring_sleep.attributes.data.deep_sleep_duration }}
        unit_of_measurement: 'h'
        friendly_name_template: Deep Sleep

...
```
